;;; Project Euler - Problem 2

;; Each new term in the Fibonacci sequence is generated by adding the
;; previous two terms. By starting with 1 and 2, the first 10 terms
;; will be:

;;     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;; By considering the terms in the Fibonacci sequence whose values do
;; not exceed four million, find the sum of the even-valued terms.

(defun euler-2 ()
  (loop with a = 1 and b = 2 until (> b 4000000)
     when (evenp b) sum b do (shiftf a b (+ a b))))
